name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at midnight UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub username
          token: ${{ secrets.METRICS_TOKEN }}

          # Base config
          user: ChoudharyNavit22
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata

          # ğŸ† Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed

          # ğŸ“Š Language stats
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming

          # ğŸ“… Week activity stats
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # ğŸ“ˆ Commit activity
          plugin_lines: yes
          plugin_lines_skipped: 10

          # Ordering
          config_order: base, achievements, languages, isocalendar, lines
